### ISSUE TITLE
How about inverted usage: relay on a not null constraint and if really nullable mark with a comment

### ISSUE THREAD

**Issue by auwtch** [graphile-contrib/pg-non-null#1]
Just because the real cases are such that nullable fields are rare.

**Comment by benjie** [comment]
The issue with that is that going from nullable to non-null is a non-breaking change, but the other way is a breaking change as any code that depends on its non-nullability could crash if it receives a null.

**Comment by benjie** [comment]
(Could still do it as an option if you're happy with that caveat though.)

**Comment by auwtch** [comment]
That's true, but in our large (react + typescript) codebase we use that approach everywhere 
```ts
response.data &&
response.data.order &&
response.data.order.items &&
response.data.order.items.nodes.map(
  node => node.employee && 
          node.employee.name && 
          getInitialsFromName(node.employee.name)
)
```
Such a code is used in 560 locations, so it hard to read and maintain. Also mark almost every column with a magic comment just increases the possibility of human error.

It will be good if we can write:
```sql
name varchar(32) not null
```
And GraphQL type of name will be `name: String!`, not `name: String` by default. But without `not null` constraint column will be nullable.

And also have magic comment to mark that column (or a reference) as nullable independent of any constraints.

**Comment by benjie** [comment]
Ummm... column values marked not null come through as non-null already, right?

**Comment by auwtch** [comment]
Wow, I feel awkward, when it was done? 😅
I think our problem is solved, thank you!

**Comment by benjie** [comment]
I wasn't aware that `not null` column values were ever not `GraphQLNonNull`'d 😁 

@enisdenjo I think you can close this.
